feat: Liftover callsets from hg19/GRCh37 to hg38/GRCh38
snakemake-workflows/dna-seq-benchmark pull request #70
Opened 2024-04-12 14:18 UTC by famosab

Still a WIP, just added some code I took from the [bcftools liftover plugin](https://github.com/freeseek/score). 
Edit: We decided to use the Picard Tool!

Open questions include

- [ ] using docker since conda not available for plugin
- [ ] how to download references, where to store
- [ ] when to do the liftover (ideally as first rule?)

(New PR since old one included commits from other feature).

2024-04-16 12:37 UTC, BiancaStoecker commented
Picard LiftoverVcf works: http://broadinstitute.github.io/picard/command-line-overview.html#LiftoverVcf

Rename contigs beforehand with: https://github.com/dpryan79/ChromosomeMappings/blob/master/GRCh37_UCSC2ensembl.txt

```
java -jar picard.jar CreateSequenceDictionary  -R genome.fasta -O genome.dict

java -jar picard.jar LiftoverVcf  -I input_renamed.vcf  -O lifted_over.vcf  --CHAIN GRCh37_to_GRCh38.chain.gz      --REJECT rejected_variants.vcf -R genome.fasta
```

Chain: `wget http://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz`

2024-04-19 08:28 UTC, BiancaStoecker commented
Liftover works for the hg19 callsets from Heidelberg

2024-04-22 08:34 UTC, johanneskoester approved these changes

2024-04-22 08:35 UTC, johanneskoester requested changes
Please add a (commented out) example with explanation to the template config in config/config.yaml.

2024-04-22 13:13 UTC, merged