feat: add version of benchmark as key in presets and include in report
snakemake-workflows/dna-seq-benchmark pull request #80
Opened 2024-06-19 11:06 UTC by famosab

2024-06-19 12:22 UTC, johanneskoester requested changes

2024-06-19 12:22 UTC, johanneskoester commented on workflow/rules/eval.smk
> +            },
Like this, it is only possible to use wildcards, but version is not a wildcard. However, you can return labels from a function, see https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html#determining-category-subcategory-and-labels-dynamically-via-functions

2024-06-19 12:23 UTC, johanneskoester commented on workflow/rules/eval.smk
> +            },
On the other hand, I am unsure whether this really should be the place where the version resides. I think it is better suited in the description of the datavzrd views.

2024-06-19 12:34 UTC, famosab commented on workflow/rules/eval.smk
> +            },
I also realized that, I am on it. Wrote a function to get the version and included it in the yte template. Its running on my machine at the moment - if it works that should be it.

2024-06-20 10:49 UTC, johanneskoester approved these changes
Fantastic work! Thanks a lot!

2024-06-20 10:49 UTC, merged